In [1]:
import numpy as np

In [12]:
height = [72, 68, 69, 64, 72, 72] # some height data in inches

# convert this data height data from inches to meters (w/o numpy):
# 1 inch = 0.0254 meter
for i in range(len(height)):
    height_m.append(height[i]*0.0254)

In [14]:
height_m

[1.8288,
 1.7271999999999998,
 1.8288,
 1.7271999999999998,
 1.7526,
 1.6256,
 1.8288,
 1.8288]

In [16]:
np_height = np.array(height)
np_height

array([72, 68, 69, 64, 72, 72])

In [17]:
np_height*0.0254 # works because of vectorization

array([1.8288, 1.7272, 1.7526, 1.6256, 1.8288, 1.8288])

In [20]:
my_list1 = [2,4,6]
my_list2 = [1,3,5]

print(my_list1 + my_list2) # appends the lists

np_mylist1 = np.array(my_list1)
np_mylist2 = np.array(my_list2)

print(np_mylist1 + np_mylist2)

[2, 4, 6, 1, 3, 5]
[ 3  7 11]


In [32]:
numbers = [1,2,3]
numbers2= [10.0, 12.1, 35.3]

print(np.array(numbers).dtype)
print(np.array(numbers2).dtype)
print(np.array(numbers,dtype='float'))
print(np.array(numbers,dtype='float').dtype)

int32
float64
[1. 2. 3.]
float64


In [33]:
age = [18,23,89,11,35,37] # some age data
np_age = np.array(age)
print(np_age)

[18 23 89 11 35 37]


In [51]:
print(np_age[2])
print(np_age[2:4])
print(np_age[:3]) # equivalent to np_age[0:3]
print(np_age[3:]) # equivalent to np_age[3:7]
print(np_age[::2]) # equivalent to np_age[0:7:2]
print(np_age[::-1]) # "steps of -1"

89
[89 11]
[18 23 89]
[11 35 37]
[18 89 35]
[37 35 11 89 23 18]


In [57]:
print(np.arange(0,5)) # python does not use the end number
print(np.arange(0,5,2))
print(np.arange(5)) # equivalent to the first line
print(np.arange(-5,5)) # works with negative numbers too
print(np.arange(4,-1,-1)) # works in reverse too

[0 1 2 3 4]
[0 2 4]
[0 1 2 3 4]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[4 3 2 1 0]


In [65]:
#np_age
print(np_age[np_age > 30]) # returns people over 30
print(np_age[(np_age >30) | (np_age<20)]) # you can two conditions (could be and "&", or "|", not "~")

[89 35 37]
[18 89 11 35 37]


In [70]:
# 2d arrays, aka matrics
height = [72, 68, 69, 64, 72, 72] # some height data in inches
weight = [200, 165, 160, 135, 200, 190] # some weight data in lbs

# create a numpy array (2d)
data = np.array([height,weight])
print(data)

[[ 72  68  69  64  72  72]
 [200 165 160 135 200 190]]


In [72]:
print(data.ndim) # returns the number of dimensions of your array
print(data.shape) # shows the object has 2 rows and 6 cols

2
(2, 6)


In [75]:
data[0,1] # element inside row 1, col 2, equilvanet to data[0][1]

68

In [76]:
data[0] # returns the entire row 1

array([72, 68, 69, 64, 72, 72])

In [88]:
data[:,1] # returns the entire col 2

array([ 68, 165])

In [94]:
x = np.arange(1,10) # creates a vector from 1 to 9 with the default step size of 1
print(x)
print(x.reshape(3,3))
print(x.resize(3,3)) # exactly the same as reshape, but it overwrites your original x vector

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
None


In [96]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
x.shape

(3, 3)

In [ ]:
# use the data below and return a bmi vector
# that contains the body mass index of
# the people in the data
# bmi = 703 * weight/height^2
# note: if you need height^2, python's synyax is height**2

# do this without numpy and with numpy

# 2d arrays, aka matrics
height = [72, 68, 69, 64, 72, 72] # some height data in inches
weight = [200, 165, 160, 135, 200, 190] # some weight data in lbs