In [1]:
import numpy as np

In [10]:
height = [72, 68, 69, 68, 64, 72] # some height data in inches

# convert each of these height data from inches to meters
# 1 inch = 0.0254 meter

height_m = []
# do this without using numpy
for i in range(0,len(height)):
    height_m.append(height[i] * 0.0254)
print(height_m)

[1.8288, 1.7271999999999998, 1.7526, 1.7271999999999998, 1.6256, 1.8288]


In [15]:
# instead use numpy which is much faster
# first create a numpy array
np_height = np.array(height)
np_height

array([72, 68, 69, 68, 64, 72])

In [16]:
np_height*0.0254

array([1.8288, 1.7272, 1.7526, 1.7272, 1.6256, 1.8288])

In [19]:
# one difference between lists and numpy arrays
print([1,2,3] + [4,5,6])
print(np.array([1,2,3]) + np.array([4,5,6]))
# I want the output: [5,7,9]

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [20]:
np.array([1,2,3]).dtype

dtype('int32')

In [22]:
np.array([1.75,2.0,3]).dtype

dtype('float64')

In [24]:
# accessing elements
age = [18,23,89,11,35,37] # some age data
np_age = np.array(age)
print(np_age)

[18 23 89 11 35 37]


In [43]:
np_age[1] # returns the the second element: 23
np_age[1:3] # returns elements 2 and 3: [23 89]
np_age[:3] # returns elements from 0 up to 3: [18 23 89]
np_age[3:] # returns the last 3 elements: [11 35 37]
np_age[::2] # returns the first, third, and the fifth elements: [18 89 35]
np_age[::-1] # returns the same array, but in reverse: [37 35 11 89 23 18]
np_age[np_age<30] # returns values with age < 30: Hint: think back to R "filtering"

array([18, 23, 11])

In [48]:
print(range(0,10,1)) # creates a list of numbers from 0 up to 9
print(np.arange(0,10,1)) # numpy array version of it
print(np.arange(9,-1,-1)) # works in the reverse direction too

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
# what if you want to return people with age <30 or age >60
# or: "|"
# and: "&"
# not: "~"
print(np_age[(np_age<30) | (np_age >60)])

[18 23 89 11]


In [59]:
# 2d arrays, aka matrices
height = [72, 68, 69, 68, 64, 72] # some height data in inches
weight = [200, 165, 160, 135, 120, 200] # some weight data in lbs

data = np.array([height,weight])
print(data)

[[ 72  68  69  68  64  72]
 [200 165 160 135 120 200]]


In [65]:
print(data.shape) # 2 rows and 6 columns
print(data.ndim)

(2, 6)
2


In [66]:
print(np_height.shape) # 1 dimensional, so only one number
print(np_height.ndim)

(6,)
1


In [67]:
data.dtype

dtype('int32')

In [77]:
data[0] # returns the first row of data: [72 68 69 68 64 72]
data[0,1] # returns the element in the first row and second col: 68, equivalen to data[0][1]
data[:,1] # returns te second column: [68 165]

array([ 68, 165])

In [82]:
# reshape() vs resize()
x = np.arange(1,10,1)
print(x)
print(x.reshape(3,3))
print(x)
x.resize(3,3) # same as reshape(), but overwrites the original object
print(x)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# calculate bmi of each person using their height and weight data
# bmi = weight / height^2
# note: for squaring numbers in python you should use : "**"
# do this without numpy and with numpy

# optional: create a function called bmi_calculator that takes in
# two lists (one for height another for weight) and returns
# the calculated bmi values as a list/numpy array


# 2d arrays, aka matrices
height = [72, 68, 69, 68, 64, 72] # some height data in inches
weight = [200, 165, 160, 135, 120, 200] # some weight data in lbs