In [9]:
import numpy as np

In [12]:
height = [72, 68, 69, 64, 72, 72] # some height data in inches

# convert this data height data from inches to meters (w/o numpy):
# 1 inch = 0.0254 meter
for i in range(len(height)):
    height_m.append(height[i]*0.0254)

In [14]:
height_m

[1.8288,
 1.7271999999999998,
 1.8288,
 1.7271999999999998,
 1.7526,
 1.6256,
 1.8288,
 1.8288]

In [16]:
np_height = np.array(height)
np_height

array([72, 68, 69, 64, 72, 72])

In [17]:
np_height*0.0254 # works because of vectorization/broadcasting

array([1.8288, 1.7272, 1.7526, 1.6256, 1.8288, 1.8288])

In [20]:
my_list1 = [2,4,6]
my_list2 = [1,3,5]

print(my_list1 + my_list2) # appends the lists

np_mylist1 = np.array(my_list1)
np_mylist2 = np.array(my_list2)

print(np_mylist1 + np_mylist2)

[2, 4, 6, 1, 3, 5]
[ 3  7 11]


In [32]:
numbers = [1,2,3]
numbers2= [10.0, 12.1, 35.3]

print(np.array(numbers).dtype)
print(np.array(numbers2).dtype)
print(np.array(numbers,dtype='float'))
print(np.array(numbers,dtype='float').dtype)

int32
float64
[1. 2. 3.]
float64


In [33]:
age = [18,23,89,11,35,37] # some age data
np_age = np.array(age)
print(np_age)

[18 23 89 11 35 37]


In [51]:
print(np_age[2])
print(np_age[2:4])
print(np_age[:3]) # equivalent to np_age[0:3]
print(np_age[3:]) # equivalent to np_age[3:7]
print(np_age[::2]) # equivalent to np_age[0:7:2]
print(np_age[::-1]) # "steps of -1"

89
[89 11]
[18 23 89]
[11 35 37]
[18 89 35]
[37 35 11 89 23 18]


In [57]:
print(np.arange(0,5)) # python does not use the end number
print(np.arange(0,5,2))
print(np.arange(5)) # equivalent to the first line
print(np.arange(-5,5)) # works with negative numbers too
print(np.arange(4,-1,-1)) # works in reverse too

[0 1 2 3 4]
[0 2 4]
[0 1 2 3 4]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[4 3 2 1 0]


In [65]:
#np_age
print(np_age[np_age > 30]) # returns people over 30
print(np_age[(np_age >30) | (np_age<20)]) # you can two conditions (could be and "&", or "|", not "~")

[89 35 37]
[18 89 11 35 37]


In [70]:
# 2d arrays, aka matrics
height = [72, 68, 69, 64, 72, 72] # some height data in inches
weight = [200, 165, 160, 135, 200, 190] # some weight data in lbs

# create a numpy array (2d)
data = np.array([height,weight])
print(data)

[[ 72  68  69  64  72  72]
 [200 165 160 135 200 190]]


In [72]:
print(data.ndim) # returns the number of dimensions of your array
print(data.shape) # shows the object has 2 rows and 6 cols

2
(2, 6)


In [75]:
data[0,1] # element inside row 1, col 2, equilvanet to data[0][1]

68

In [76]:
data[0] # returns the entire row 1

array([72, 68, 69, 64, 72, 72])

In [88]:
data[:,1] # returns the entire col 2

array([ 68, 165])

In [94]:
x = np.arange(1,10) # creates a vector from 1 to 9 with the default step size of 1
print(x)
print(x.reshape(3,3))
print(x.resize(3,3)) # exactly the same as reshape, but it overwrites your original x vector

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
None


In [96]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
x.shape

(3, 3)

In [21]:
y = np.arange(1,16)
print(y)
y.reshape(5,-1) # -1 wildcard

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
# use the data below and return a bmi vector
# that contains the body mass index of
# the people in the data
# bmi = 703 * weight/height^2
# note: if you need height^2, python's synyax is height**2

# do this without numpy and with numpy

# 2d arrays, aka matrices
height = [72, 68, 69, 64, 72, 72] # some height data in inches
weight = [200, 165, 160, 135, 200, 190] # some weight data in lbs

# without numpy
#for i in range(len(height)):
#    print(703 * weight[i] / height[i]**2)
    
np_height = np.array(height)
np_weight = np.array(weight)

#print(703 * np_weight/np_height**2)

# you can always round decimal with the np.round()
print(np.round(703 * np_weight/np_height**2,4))

[27.1219 25.0854 23.6253 23.1702 27.1219 25.7658]


In [22]:
m = [[10,11,12,13,14],[1,2,3,4,5],[20,21,22,23,24]]
print(m)

[[10, 11, 12, 13, 14], [1, 2, 3, 4, 5], [20, 21, 22, 23, 24]]


In [34]:
print(np.sum(m))
print(np.sum(m,axis=0))
print(np.sum(m,axis=1))

185
[31 34 37 40 43]
[ 60  15 110]


In [43]:
# some more statistical funcs to know
print(m[0])
print(np.median(m[0]))
print(np.mean(m[0]))
print(np.min(m[0]))
print(np.max(m[0]))
print(np.std(m[0]))

# some funcs to know for numerical computation
print(np.pi)
print(np.sin(0))
print(np.rad2deg(np.pi))
print(np.deg2rad(180))

[10, 11, 12, 13, 14]
12.0
12.0
10
14
1.4142135623730951
3.141592653589793
0.0
180.0
3.141592653589793


In [46]:
threeD = np.array([[[10,20,30],[40,50,60]],[[15,25,35],[45,55,65]],[[70,80,90],[75,85,95]]])
print(threeD) # this is a array of matrices

[[[10 20 30]
  [40 50 60]]

 [[15 25 35]
  [45 55 65]]

 [[70 80 90]
  [75 85 95]]]


In [53]:
print(threeD[0]) # returns the first matrix
print(threeD[0,1]) # first number: matrix pos; second is: row position
print(threeD[0,0,1]) # first number: matrix pos; second is: row position, third is: col position
print(threeD.shape)
print(threeD.ndim)

[[10 20 30]
 [40 50 60]]
[40 50 60]
20
(3, 2, 3)
3


In [62]:
# broadcasting
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
print(a)
b = np.array([0,1,2])
print(b)
print(a+b) # works! note the dimensions 4x3 and 1x3, with broadcasting second becomes 4x3 too.
c = np.array([0,1,2,3])
print(c)
#print(a+c) # incompatible
# practice: change c such that a+c becomes valid, hint: use resize()
print(a+c.T)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[0 1 2 3]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [69]:
x = np.ones((3,3))
y = np.ones((1,4))

#print(x+y) incompatible
x = np.ones((2,5,1,8,4))
y = np.ones((5,1,8,1))
print(x)
print(y)

[[[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]]]


  [[[1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
    [1. 1. 1. 1.]
  